team-winey/Winey-Server

- src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
- src/main/java/org/winey/server/controller/RecommendController.java
- src/main/java/org/winey/server/controller/response/PageResponseDto.java
- src/main/java/org/winey/server/controller/response/recommend/RecommendListResponseDto.java
- src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
- src/main/java/org/winey/server/controller/response/recommend/RecommendResponseUserDto.java
- src/main/java/org/winey/server/domain/recommend/Recommend.java
- src/main/java/org/winey/server/exception/Error.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/infrastructure/RecommendRepository.java
- src/main/java/org/winey/server/infrastructure/UserRepository.java
- src/main/java/org/winey/server/service/RecommendService.java
- close #7 
- RecommendListResponseDto 안에  RecommendResponseUserDto, PageResponseDto, RecommendResponseDto를 필드로 넣어 response 데이터 생성하였습니다! dto-reponse 부분이랑 service 부분 참고해주세요!! (혹시 더 좋은 방법 있으면 알려주세요!!)
- requestHeader, requestParameter 없는 경우 예외 처리 `ControllerExceptionAdvice.java`에 추가해두었습니다!
- 조회 성공
- 헤더가 없는 경우
- 파라미터가 없는 경우
- 존재하지 않는 유저인 경우
[GET] ~/recommend?page=0
> [Feat] getRecommend

- src/main/java/org/winey/server/ServerApplication.java
- src/main/java/org/winey/server/controller/GoalController.java
- src/main/java/org/winey/server/controller/request/goal/GoalRequestCreateDto.java
- src/main/java/org/winey/server/controller/response/goal/GoalResponseCreateDto.java
- src/main/java/org/winey/server/domain/goal/Goal.java
- src/main/java/org/winey/server/domain/user/User.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/infrastructure/GoalRepository.java
- src/main/java/org/winey/server/infrastructure/RecommendRepository.java
- src/main/java/org/winey/server/infrastructure/UserRepository.java
- src/main/java/org/winey/server/service/GoalService.java
- close #9 
새로운 goal을 DB에 넣을 때 default 값이 지정된 필드였던 `duringGoalAmount`, `isAttained` 값이 null로 반영돼서 우선 빌더(생성자)에 직접 주입하는 방식으로 `Goal.java` 변경하였습니다! 찾아보니깐 이렇게도 하는 것 같더라구요... 
다른 방법 있으면 알려주세요!!🥲
```java
@Builder
public Goal(Long targetMoney, LocalDate targetDate, User user) {
this.targetMoney = targetMoney;
this.targetDate = targetDate;
this.user = user;
this.duringGoalAmount = 0L;
this.isAttained = false;
}
```
- 목표 생성 성공
- targetMoney가 30000원 미만일 경우
- targetDate가 15일 미만일 경우
- userId가 헤더에 없는 경우
[POST] ~/goal
> [Feat] createGoal 

- src/main/java/org/winey/server/ServerApplication.java
- src/main/java/org/winey/server/controller/FeedController.java
- src/main/java/org/winey/server/controller/feed/FeedController.java
- src/main/java/org/winey/server/controller/request/CreateFeedRequestDto.java
- src/main/java/org/winey/server/controller/response/feed/CreateFeedResponseDto.java
- src/main/java/org/winey/server/domain/feed/Feed.java
- src/main/java/org/winey/server/domain/goal/Goal.java
- src/main/java/org/winey/server/domain/user/User.java
- src/main/java/org/winey/server/exception/Error.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/exception/model/ForbiddenException.java
- src/main/java/org/winey/server/infrastructure/FeedRepository.java
- src/main/java/org/winey/server/infrastructure/GoalRepository.java
- src/main/java/org/winey/server/service/FeedService.java
- close #12 
url 변경 및 createFeed 미완된 리팩터링
- /feed/{feedId}
> Feat/#12 피드 삭제하기 구현

- src/main/java/org/winey/server/controller/FeedController.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/infrastructure/FeedRepository.java
- src/main/java/org/winey/server/service/FeedService.java
- close #23 
원래 있었던 getAllFeed에서 사용했던 페이지네이션 등을 활용 하여 작성했습니다. 🌱
case1. 유저의 작성한 피드가 없을 때
case2. 유저의 작성한 피드가 있을 때
- /feed/myFeed?page={int}
> #23 [Feat] getMyFeed 구현하기

- build.gradle
- src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
- src/main/java/org/winey/server/controller/SlackTestController.java
- src/main/java/org/winey/server/slack/SlackApi.java
> [Feat] 슬랙 500 알림

- src/main/java/org/winey/server/controller/FeedController.java
- src/main/java/org/winey/server/controller/FeedLikeController.java
- src/main/java/org/winey/server/controller/RecommendController.java
- src/main/java/org/winey/server/controller/response/feed/GetFeedResponseDto.java
- src/main/java/org/winey/server/controller/response/feedLike/CreateFeedLikeResponseDto.java
- src/main/java/org/winey/server/service/FeedLikeService.java
- src/main/java/org/winey/server/service/FeedService.java
> [Fix] 좋아요 수 Long 타입으로 변경

- src/main/java/org/winey/server/service/RecommendService.java
> [Fix] 금액 response 할 때 콤마 표기 추가

- src/main/java/org/winey/server/service/FeedService.java
- src/main/java/org/winey/server/service/RecommendService.java
- src/main/java/org/winey/server/service/UserService.java
> [Fix] 추천 위니 페이지네이션 수 바꾸기, d-day 계산 수정

- scripts/deploy.sh
- src/main/java/org/winey/server/service/FeedService.java
- src/main/java/org/winey/server/service/RecommendService.java
- src/main/java/org/winey/server/service/UserService.java
> main에 dday 로직수정 merge

- src/main/java/org/winey/server/domain/feed/Feed.java
- src/main/java/org/winey/server/domain/feed/FeedLike.java
> [Feat] FeedLike - Feed cascade 추가

- src/main/java/org/winey/server/service/RecommendService.java
> [Fix] 추천 위니 pagination 한 페이지당 20으로 업데이트

- src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
> [Fix] responseDto NON_NULL 제거

- src/main/java/org/winey/server/common/advice/ControllerExceptionAdvice.java
- src/main/java/org/winey/server/controller/response/recommend/RecommendResponseDto.java
- src/main/java/org/winey/server/exception/Error.java
> HttpRequestMethodNotSupportedException 예외 처리 배포

- src/main/java/org/winey/server/controller/FeedController.java
- src/main/java/org/winey/server/controller/request/CreateFeedRequestDto.java
- src/main/java/org/winey/server/controller/request/goal/GoalRequestCreateDto.java
- src/main/java/org/winey/server/exception/Error.java
> [Feat] 위니피드, 목표 제한

- build.gradle
- src/main/java/org/winey/server/ServerApplication.java
- src/main/java/org/winey/server/config/jwt/JwtService.java
- src/main/java/org/winey/server/controller/AuthController.java
- src/main/java/org/winey/server/controller/request/auth/SignInRequestDto.java
- src/main/java/org/winey/server/controller/response/auth/SignInResponseDto.java
- src/main/java/org/winey/server/domain/user/SocialType.java
- src/main/java/org/winey/server/domain/user/User.java
- src/main/java/org/winey/server/exception/Error.java
- src/main/java/org/winey/server/infrastructure/UserRepository.java
- src/main/java/org/winey/server/service/auth/AuthService.java
- src/main/java/org/winey/server/service/auth/apple/AppleSignInService.java
- src/main/java/org/winey/server/service/auth/apple/feign/AppleApiClient.java
- src/main/java/org/winey/server/service/auth/apple/response/ApplePublicKey.java
- src/main/java/org/winey/server/service/auth/apple/response/ApplePublicKeys.java
- src/main/java/org/winey/server/service/auth/apple/verify/AppleJwtParser.java
- src/main/java/org/winey/server/service/auth/apple/verify/EncryptUtils.java
- src/main/java/org/winey/server/service/auth/apple/verify/PublicKeyGenerator.java
> [Feat] 소셜 로그인 세팅 및 애플 로그인 구현

- src/main/java/org/winey/server/controller/response/comment/CreateCommentResponseDto.java
- src/main/java/org/winey/server/service/CommentService.java
- close #100 
user를 response dto에 넣으니 연관된 모든 db들이 딸려나와서 일단 생성에는 author를 string 값으로 넣음.
> [Fix] 변경사항 다시 적용

- src/main/java/org/winey/server/service/auth/AuthService.java
> [Test] infinity token

- src/main/java/org/winey/server/service/FeedService.java
- src/main/java/org/winey/server/service/NotiService.java
> [Fix] timeAgo 시간 추가

- src/main/java/org/winey/server/controller/CommentController.java
- src/main/java/org/winey/server/controller/response/comment/DeleteCommentResponseDto.java
- src/main/java/org/winey/server/service/CommentService.java
> [Refactor] 댓글삭제시 댓글id 보내주기

- src/main/java/org/winey/server/service/auth/AuthService.java
> [Test] 엑세스토큰 리프레시토큰 시간변경

- src/main/java/org/winey/server/service/auth/AuthService.java
> [Test] 아요 토큰 테스트

- src/main/java/org/winey/server/service/auth/AuthService.java
infinity token
엑세스 100일
리프레시 300일
> [Test] 아요 토큰 테스트 종료

- src/main/java/org/winey/server/service/auth/AuthService.java
> [Test] 마지막 테스트 토큰

- src/main/java/org/winey/server/service/FeedService.java
- src/main/java/org/winey/server/service/UserService.java
- close #154 
- 기한 내 목표 달성 시 기한 종료 강제로 false로 바꾸지 않는다
- 누적 위니, 횟수 살려서 보낸다
```java
```
- /
> [Fix] 마이페이지 수정

- src/main/java/org/winey/server/domain/feed/Feed.java
- src/main/java/org/winey/server/domain/goal/Goal.java
- src/main/java/org/winey/server/service/FeedService.java
> [Fix] 피드 삭제 관련 오류

- src/main/java/org/winey/server/controller/BlockController.java
- src/main/java/org/winey/server/domain/block/BlockUser.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/infrastructure/BlockUserRepository.java
- src/main/java/org/winey/server/infrastructure/FeedRepository.java
- src/main/java/org/winey/server/service/BlockService.java
- src/main/java/org/winey/server/service/FeedService.java
- close #175 
- Block 테이블 생성 (차단한 유저 아이디, 차단 당한 유저 아아디)
- 유저 차단 API
- 피드 조회 시 내가 차단한 유저의 게시글은 제외
```java
```
- /
> [Feat] 유저 차단 기능

- src/main/java/org/winey/server/infrastructure/BlockUserRepository.java
- src/main/java/org/winey/server/service/auth/AuthService.java
> #175 [Feat] 회원 탈퇴시 차단 목록 제거

- .gitignore
- build.gradle
- src/main/java/org/winey/server/config/SchedulerConfig.java
- src/main/java/org/winey/server/service/NotiService.java
- src/main/resources/logback-spring.xml
> [Fix] 목표 달성 실패 알림 중복 발송 문제 해결

- .github/workflows/cd.yml
- .github/workflows/gradle.yml
- .gitignore
- build.gradle
- src/main/java/org/winey/server/common/message/MessageQueueReceiver.java
- src/main/java/org/winey/server/common/message/MessageQueueSender.java
- src/main/java/org/winey/server/controller/UserController.java
- src/main/java/org/winey/server/controller/request/UpdateAllowedPushDto.java
- src/main/java/org/winey/server/controller/request/UpdateFcmTokenDto.java
- src/main/java/org/winey/server/controller/request/auth/SignInRequestDto.java
- src/main/java/org/winey/server/controller/response/auth/SignInResponseDto.java
- src/main/java/org/winey/server/controller/response/user/UserResponseUserDto.java
- src/main/java/org/winey/server/domain/user/User.java
- src/main/java/org/winey/server/exception/Error.java
- src/main/java/org/winey/server/exception/Success.java
- src/main/java/org/winey/server/service/CommentService.java
- src/main/java/org/winey/server/service/FcmService.java
- src/main/java/org/winey/server/service/FeedLikeService.java
- src/main/java/org/winey/server/service/FeedService.java
- src/main/java/org/winey/server/service/NotiService.java
- src/main/java/org/winey/server/service/UserService.java
- src/main/java/org/winey/server/service/auth/AuthService.java
- src/main/java/org/winey/server/service/message/FcmRequestDto.java
> feat: FCM 배포

- src/main/java/org/winey/server/domain/user/User.java
- src/main/java/org/winey/server/service/CommentService.java
- src/main/java/org/winey/server/service/FeedLikeService.java
> feat: getFCMToken 메서드를 오버라이드한다.

- src/main/java/org/winey/server/common/message/MessageQueueReceiver.java
- close #201 
Notification으로 타입체크를 하고 있는 것을 찾아버렸습니다.. 
- /fcm comment
> [Bug] 댓글 알림 안가는 이슈 해결

- src/main/java/org/winey/server/common/message/MessageQueueReceiver.java
- src/main/java/org/winey/server/service/FcmService.java
> [Merge] 댓글알림 버그 해결
